server:
  port: 8081

spring:
  application:
    name: dubbo-provider

# Dubbo配置
dubbo:
  application:
    name: dubbo-provider
    logger: slf4j
  
  # 协议配置
  protocol:
    name: dubbo
    port: 20880
  
  # 注册中心配置
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
  
  # 提供者配置
  provider:
    timeout: 5000
    retries: 0
    delay: 0
    
  # 元数据配置
  metadata-report:
    address: zookeeper://127.0.0.1:2181

# 日志配置
logging:
  level:
    com.example.dubbo: DEBUG
    org.apache.dubbo: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 