server:
  port: 8051
  address: 0.0.0.0

spring:
  application:
    name: mcp-router-v2.01
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        enabled: true
        sse-endpoint: /sse
        tools-enabled: false
    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          registry:
            enabled: true
            service-group: mcp-server
            service-name: ${spring.application.name}
        
logging:
  level:
    root: INFO
    com.nacos.mcp.router.v2: DEBUG
    org.springframework.ai: DEBUG
    com.alibaba.cloud.ai: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics