spring:
  application:
    name: mcp-router
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        group: mcp-server
        enabled: true
      config:
        enabled: false
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    default-property-inclusion: NON_NULL
    deserialization:
        fail-on-unknown-properties: false
        accept-single-value-as-array: true
  # MCP 配置
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-router
        description: MCP Router Service
        version: 1.0.0

server:
  port: 8060  # 修改为正确的端口号
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.nacos.mcp.router: DEBUG
    org.springframework.ai: INFO
    org.springframework.web: INFO

# MCP Router Configuration
mcp-router:
  discovery:
    enabled: true
    provider: nacos
  cache:
    enabled: true
    ttl: 300  # 5 minutes
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  security:
      enabled: false

